class CitiesData {
  static final Map<String, List<String>> citiesByCountry = {
    'Pakistan': [
      'Karachi',
      'Lahore',
      'Islamabad',
      'Rawalpindi',
      'Faisalabad',
      'Multan',
      'Peshawar',
      'Abbottabad',
      'Quetta',
      'Sialkot',
      'Gujranwala',
      'Hyderabad',
      'Sukkur',
      'Larkana',
      'Nawabshah',
      'Mirpur Khas',
      'Jacobabad',
      'Shikarpur',
      'Dadu',
      'Khairpur',
      'Matiari',
      'Tando Allahyar',
      'Tando Muhammad Khan',
      'Badin',
      'Thatta',
      'Jamshoro',
      'Kotri',
      'Kandhkot',
      'Kashmore',
      'Ghotki',
      'Sanghar',
      'Umerkot',
      'Tharparkar',
      'Mardan',
      'Swat',
      'Mingora',
      'Kohat',
      'Bannu',
      'Dera Ismail Khan',
      'Tank',
      'Chitral',
      'Gilgit',
      'Skardu',
      'Muzaffarabad',
      'Mirpur',
      'Bhimber',
      'Kotli',
      'Sialkot',
      'Gujrat',
      'Jhelum',
      'Sargodha',
      'Sheikhupura',
      'Kasur',
      'Okara',
      'Sahiwal',
      'Pakpattan',
      'Vehari',
      'Khanewal',
      'Lodhran',
      'Bahawalpur',
      'Rahim Yar Khan',
      'Bahawalnagar',
      'Chishtian',
      'Hasilpur',
      'Ahmadpur East',
      'Dera Ghazi Khan',
      'Taunsa',
      'Jampur',
      'Rajanpur',
      'Layyah',
      'Bhakkar',
      'Mianwali',
      'Attock',
      'Talagang',
      'Chakwal',
      'Jhelum',
      'Gujar Khan',
      'Rawalpindi',
      'Murree',
      'Taxila',
      'Wah Cantonment',
      'Hassan Abdal',
      'Haripur',
      'Havelian',
      'Mansehra',
      'Battagram',
      'Allai',
      'Balakot',
      'Shinkiari',
      'Oghi',
      'Darband',
      'Khanpur',
      'Hafizabad',
      'Wazirabad',
      'Gujranwala',
      'Kamoke',
      'Nankana Sahib',
      'Sangla Hill',
      'Chichawatni',
      'Chunian',
      'Raiwind',
      'Kot Radha Kishan',
      'Pattoki',
      'Phool Nagar',
      'Depalpur',
      'Renala Khurd',
      'Arifwala',
      'Burewala',
      'Vehari',
      'Mailsi',
      'Dunyapur',
      'Lodhran',
      'Kahror Pakka',
      'Karor Lal Esan',
      'Layyah',
      'Kot Addu',
      'Muzaffargarh',
      'Alipur',
      'Jatoi',
      'Shujabad',
      'Multan',
      'Shujaabad',
      'Jalalpur Pirwala',
      'Mian Channu',
      'Kabirwala',
      'Khanewal',
      'Tulamba',
      'Makhdoompur',
      'Ahmadpur Sial',
      'Bahawalpur',
      'Bahawalnagar',
      'Chishtian',
      'Haroonabad',
      'Fort Abbas',
      'Minchinabad',
      'Hasilpur',
      'Dera Nawab Sahib',
      'Ahmadpur East',
      'Liaquatpur',
      'Rahim Yar Khan',
      'Khanpur',
      'Sadiqabad',
      'Uch Sharif',
      'Dera Ghazi Khan',
      'Taunsa',
      'Jampur',
      'Kotla Arab Ali Khan',
      'Rajanpur',
      'Jampur',
    ],
    'India': [
      'Mumbai',
      'Delhi',
      'Bangalore',
      'Hyderabad',
      'Chennai',
      'Kolkata',
      'Pune',
      'Ahmedabad',
      'Jaipur',
      'Surat',
      'Lucknow',
      'Kanpur',
      'Nagpur',
      'Indore',
      'Thane',
      'Bhopal',
      'Visakhapatnam',
      'Patna',
      'Vadodara',
      'Ghaziabad',
      'Ludhiana',
      'Agra',
      'Nashik',
      'Faridabad',
      'Meerut',
      'Rajkot',
      'Varanasi',
      'Srinagar',
      'Amritsar',
      'Jodhpur',
      'Raipur',
      'Allahabad',
      'Coimbatore',
      'Jabalpur',
      'Gwalior',
      'Vijayawada',
      'Madurai',
      'Guwahati',
      'Chandigarh',
      'Hubli',
      'Amravati',
      'Bareilly',
      'Moradabad',
      'Gurgaon',
      'Aligarh',
      'Solapur',
      'Ranchi',
      'Jalandhar',
      'Tiruchirappalli',
      'Bhubaneswar',
      'Salem',
    ],
    'Bangladesh': [
      'Dhaka',
      'Chittagong',
      'Khulna',
      'Rajshahi',
      'Sylhet',
      'Barisal',
      'Rangpur',
      'Comilla',
      'Narayanganj',
      'Gazipur',
      'Mymensingh',
      'Jessore',
      'Cox\'s Bazar',
      'Bogra',
      'Dinajpur',
      'Pabna',
      'Saidpur',
      'Tangail',
      'Jamalpur',
      'Kushtia',
      'Feni',
      'Noakhali',
      'Lakshmipur',
      'Chandpur',
      'Brahmanbaria',
      'Narsingdi',
      'Manikganj',
      'Munshiganj',
      'Faridpur',
      'Gopalganj',
      'Madaripur',
      'Shariatpur',
      'Rajbari',
      'Kishoreganj',
      'Netrokona',
      'Sherpur',
      'Moulvibazar',
      'Habiganj',
      'Sunamganj',
      'Natore',
      'Naogaon',
      'Chapainawabganj',
      'Joypurhat',
      'Sirajganj',
      'Magura',
      'Jhenaidah',
      'Meherpur',
      'Chuadanga',
      'Jashore',
      'Satkhira',
      'Bagerhat',
      'Pirojpur',
      'Jhalokathi',
      'Bhola',
      'Patuakhali',
      'Barguna',
      'Bandarban',
      'Rangamati',
      'Khagrachhari',
    ],
    'Afghanistan': [
      'Kabul',
      'Kandahar',
      'Herat',
      'Mazar-i-Sharif',
      'Kunduz',
      'Jalalabad',
      'Ghazni',
      'Balkh',
      'Baghlan',
      'Gardez',
      'Khost',
      'Lashkar Gah',
      'Taloqan',
      'Farah',
      'Pul-e-Khumri',
      'Charikar',
      'Shibirghan',
      'Asadabad',
      'Aibak',
      'Zaranj',
      'Fayzabad',
      'Qalat',
      'Mehtar Lam',
      'Bamyan',
    ],
    'United States': [
      'New York',
      'Los Angeles',
      'Chicago',
      'Houston',
      'Phoenix',
      'Philadelphia',
      'San Antonio',
      'San Diego',
      'Dallas',
      'San Jose',
      'Austin',
      'Jacksonville',
      'Fort Worth',
      'Columbus',
      'Charlotte',
      'San Francisco',
      'Indianapolis',
      'Seattle',
      'Denver',
      'Washington',
      'Boston',
      'El Paso',
      'Detroit',
      'Nashville',
      'Portland',
      'Memphis',
      'Oklahoma City',
      'Las Vegas',
      'Louisville',
      'Baltimore',
    ],
    'United Kingdom': [
      'London',
      'Birmingham',
      'Manchester',
      'Glasgow',
      'Liverpool',
      'Leeds',
      'Edinburgh',
      'Sheffield',
      'Bristol',
      'Cardiff',
      'Belfast',
      'Newcastle',
      'Nottingham',
      'Leicester',
      'Coventry',
      'Sunderland',
      'Bradford',
      'Brighton',
      'Hull',
      'Reading',
    ],
    'Canada': [
      'Toronto',
      'Montreal',
      'Vancouver',
      'Calgary',
      'Edmonton',
      'Ottawa',
      'Winnipeg',
      'Quebec City',
      'Hamilton',
      'Kitchener',
      'London',
      'Victoria',
      'Halifax',
      'Oshawa',
      'Windsor',
      'Saskatoon',
      'Regina',
      'Sherbrooke',
      'St. John\'s',
      'Barrie',
    ],
    'Australia': [
      'Sydney',
      'Melbourne',
      'Brisbane',
      'Perth',
      'Adelaide',
      'Gold Coast',
      'Newcastle',
      'Canberra',
      'Sunshine Coast',
      'Wollongong',
      'Hobart',
      'Geelong',
      'Townsville',
      'Cairns',
      'Darwin',
      'Toowoomba',
      'Ballarat',
      'Bendigo',
      'Albury',
      'Launceston',
    ],
    'China': [
      'Beijing',
      'Shanghai',
      'Guangzhou',
      'Shenzhen',
      'Tianjin',
      'Wuhan',
      'Chengdu',
      'Nanjing',
      'Xi\'an',
      'Hangzhou',
      'Dongguan',
      'Foshan',
      'Shenyang',
      'Harbin',
      'Qingdao',
      'Dalian',
      'Jinan',
      'Zhengzhou',
      'Changsha',
      'Kunming',
      'Taiyuan',
      'Shijiazhuang',
      'Nanchang',
      'Hefei',
      'Fuzhou',
      'Xiamen',
      'Guiyang',
      'Haikou',
      'Lanzhou',
      'Urumqi',
    ],
    'Japan': [
      'Tokyo',
      'Osaka',
      'Kyoto',
      'Yokohama',
      'Nagoya',
      'Sapporo',
      'Fukuoka',
      'Kobe',
      'Kawasaki',
      'Saitama',
      'Hiroshima',
      'Sendai',
      'Kitakyushu',
      'Chiba',
      'Sakai',
      'Niigata',
      'Hamamatsu',
      'Kumamoto',
      'Sagamihara',
      'Okayama',
      'Shizuoka',
      'Hachioji',
      'Honcho',
      'Matsudo',
      'Kawaguchi',
      'Kanazawa',
      'Utsunomiya',
      'Oita',
      'Matsuyama',
      'Amagasaki',
    ],
    'South Korea': [
      'Seoul',
      'Busan',
      'Incheon',
      'Daegu',
      'Daejeon',
      'Gwangju',
      'Suwon',
      'Ulsan',
      'Changwon',
      'Goyang',
      'Seongnam',
      'Bucheon',
      'Ansan',
      'Anyang',
      'Jeonju',
      'Cheonan',
      'Namyangju',
      'Hwaseong',
      'Gimhae',
      'Pyeongtaek',
    ],
    'Saudi Arabia': [
      'Riyadh',
      'Jeddah',
      'Mecca',
      'Medina',
      'Dammam',
      'Khobar',
      'Taif',
      'Abha',
      'Tabuk',
      'Buraidah',
      'Khamis Mushait',
      'Hail',
      'Najran',
      'Al Jubail',
      'Yanbu',
      'Al Kharj',
      'Arar',
      'Sakakah',
      'Jizan',
      'Dhahran',
    ],
    'United Arab Emirates': [
      'Dubai',
      'Abu Dhabi',
      'Sharjah',
      'Ajman',
      'Ras Al Khaimah',
      'Fujairah',
      'Umm Al Quwain',
      'Al Ain',
      'Al Gharbia',
      'Al Dhafra',
      'Liwa',
      'Madinat Zayed',
      'Ruwais',
      'Ghayathi',
      'Sila',
      'Delma Island',
      'Sir Bani Yas',
      'Marawah',
    ],
    'Turkey': [
      'Istanbul',
      'Ankara',
      'Izmir',
      'Bursa',
      'Antalya',
      'Gaziantep',
      'Konya',
      'Mersin',
      'Diyarbakir',
      'Kayseri',
      'Eskisehir',
      'Urfa',
      'Malatya',
      'Samsun',
      'Kahramanmaras',
      'Van',
      'Batman',
      'Denizli',
      'Elazig',
      'Erzurum',
    ],
    'Germany': [
      'Berlin',
      'Hamburg',
      'Munich',
      'Cologne',
      'Frankfurt',
      'Stuttgart',
      'Düsseldorf',
      'Dortmund',
      'Essen',
      'Leipzig',
      'Bremen',
      'Dresden',
      'Hannover',
      'Nuremberg',
      'Duisburg',
      'Bochum',
      'Wuppertal',
      'Bielefeld',
      'Bonn',
      'Münster',
    ],
    'France': [
      'Paris',
      'Marseille',
      'Lyon',
      'Toulouse',
      'Nice',
      'Nantes',
      'Strasbourg',
      'Montpellier',
      'Bordeaux',
      'Lille',
      'Rennes',
      'Reims',
      'Le Havre',
      'Saint-Étienne',
      'Toulon',
      'Grenoble',
      'Dijon',
      'Angers',
      'Nîmes',
      'Villeurbanne',
    ],
    'Italy': [
      'Rome',
      'Milan',
      'Naples',
      'Turin',
      'Palermo',
      'Genoa',
      'Bologna',
      'Florence',
      'Bari',
      'Catania',
      'Venice',
      'Verona',
      'Messina',
      'Padua',
      'Trieste',
      'Brescia',
      'Taranto',
      'Prato',
      'Modena',
      'Reggio Calabria',
    ],
    'Spain': [
      'Madrid',
      'Barcelona',
      'Valencia',
      'Seville',
      'Zaragoza',
      'Málaga',
      'Murcia',
      'Palma',
      'Las Palmas',
      'Bilbao',
      'Alicante',
      'Córdoba',
      'Valladolid',
      'Vigo',
      'Gijón',
      'Hospitalet',
      'Vitoria',
      'A Coruña',
      'Elche',
      'Granada',
    ],
    'Netherlands': [
      'Amsterdam',
      'Rotterdam',
      'The Hague',
      'Utrecht',
      'Eindhoven',
      'Groningen',
      'Tilburg',
      'Almere',
      'Breda',
      'Nijmegen',
      'Enschede',
      'Haarlem',
      'Arnhem',
      'Zaanstad',
      'Amersfoort',
      'Apeldoorn',
      '\'s-Hertogenbosch',
      'Hoofddorp',
      'Maastricht',
      'Leiden',
    ],
    'Russia': [
      'Moscow',
      'Saint Petersburg',
      'Novosibirsk',
      'Yekaterinburg',
      'Kazan',
      'Nizhny Novgorod',
      'Chelyabinsk',
      'Samara',
      'Omsk',
      'Rostov-on-Don',
      'Ufa',
      'Krasnoyarsk',
      'Voronezh',
      'Perm',
      'Volgograd',
      'Saratov',
      'Krasnodar',
      'Tolyatti',
      'Tyumen',
      'Izhevsk',
    ],
    'Malaysia': [
      'Kuala Lumpur',
      'George Town',
      'Ipoh',
      'Shah Alam',
      'Petaling Jaya',
      'Klang',
      'Johor Bahru',
      'Subang Jaya',
      'Kuching',
      'Kota Kinabalu',
      'Kuala Terengganu',
      'Kota Bharu',
      'Alor Setar',
      'Kangar',
      'Kuantan',
      'Malacca',
      'Seremban',
      'Putrajaya',
      'Cyberjaya',
      'Kajang',
      'Ampang',
      'Cheras',
    ],
  };

  static List<String> get countries => citiesByCountry.keys.toList();

  static List<String> getCitiesForCountry(String country) {
    return citiesByCountry[country] ?? [];
  }
}

